language: node_js
node_js:
  - node
  - 14
env:
  global:
    - COVERALLS_PARALLEL=true
    - COVERALLS_SERVICE_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=bV5KSrOjWkMuVxQfLxpm6wuQ1Ij46hugF
    - COVERALLS_GIT_BRANCH=main
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
branches:
  only:
    - main
git:
  lfs_skip_smudge: true
script: npm run test
cache:
  - npm
  - packages
dist: xenial
os:
  - linux
jobs:
  fast_finish: true
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=bV5KSrOjWkMuVxQfLxpm6wuQ1Ij46hugF
  email: restuwahyu13@gmail.com
